### ISSUE TITLE
Inaccurate rspec dis in the README

### ISSUE THREAD

**Issue by dchelimsky** [sconover/wrong#22]
From the wrong README:

> And in what human language is "should greater than" a valid phrase?

It's not in human languages, or RSpec. The correct use of ">" is:

```
BleuCheese.new.smell.should be > 9000
```

You may still prefer `assert { BleuCheese.new.smell > 9000 }`, but at least you're preferring it over the right thing.

FWIW, what's in the wrong README _will work_, but that's only to support people who don't bother to RTFM: http://rubydoc.info/gems/rspec-expectations#Comparisons

**Comment by alexch** [comment]
dis disabled in 9afcf18c78b42a6e6436d131f32432176a4d33aa
