### ISSUE TITLE
Cannot install 'wrong' gem because of sexp_processor dependency

### ISSUE THREAD

**Issue by nyarlathotep77** [sconover/wrong#27]
After having built the gem with the command:
- gem build wrong.gemspec
  I tried to install it with the command:
- gem install wrong-0.6.3.gem
  but I got the following error:
- ERROR:  While executing gem ... (Gem::DependencyError)
  Unable to resolve dependencies: wrong requires sexp_processor (>= 4.0); sourcify requires sexp_processor (>= 3.0.5); ParseTree requires sexp_processor (~> 3.2.0); ruby2ruby requires sexp_processor (~> 4.0); ruby_parser requires sexp_processor (~> 4.1)

The dependencies on sexp_processor don't seem can all be satisfied, as ParseTree dependes on a version which can't satisfy all the others.

My environment is:
Windows 7 64bit, Ruby 1.9.3

**Comment by alexch** [comment]
The current version of Wrong is 0.7.0 and it should correct all those
dependency problems.

Looks like I forgot to push those changes to the sconover fork though. I'll
do that right now.

**Comment by nyarlathotep77** [comment]
Thank you very much, this is fixed now.
