### ISSUE TITLE
1 tests, 0 assertions

### ISSUE THREAD

**Issue by robotarmy** [sconover/wrong#3]
How can Wrong's assert {} be counted as an assertion ?

**Comment by robotarmy** [comment]
i am also getting   1) Error:
test_has_one_user_status(ReviewTest):
NameError: undefined local variable or method `failure_class' for #<Wrong::Chunk:0x10b01d5b8>
    wrong (0.4.2) lib/wrong/chunk.rb:136:in`code'
    wrong (0.4.2) lib/wrong/assert.rb:64:in `full_message'
    wrong (0.4.2) lib/wrong/assert.rb:99:in`aver'
    wrong (0.4.2) lib/wrong/assert.rb:34:in `assert'
    test/unit/review_test.rb:123:in`test_has_one_user_status'

My version of  ruby_parser-2.0.4 and  sexp_processor-3.0.4 caused this and the above issue

  ruby_parser-2.0.5 and  sexp_processor-3.0.5

 fixed this for me.

**Comment by thenrio** [comment]
I expect {} to evaluate err ... no code
What is the value of testing no code ?
Curious, Thierry
